name: Main Workflow

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  main:
    name: Main Job
    runs-on: macos-12
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Mint
        run: brew install mint

      - name: Install Mint Packages
        run: mint bootstrap

      - name: Run Swiftlint
        run: ./scripts/lint.sh
