name: Main Workflow

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  main:
    name: Main Job
    runs-on: macos-12
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache Mint packages
        id: mint-cache-v2
        uses: actions/cache@v3
        with:
          path: ~/.mint
          key: ${{ runner.os }}-mint-${{ hashFiles('Mintfile') }}
          restore-keys: ${{ runner.os }}-mint-

      - name: Install Mint
        run: brew install mint

      - name: Install Mint Packages
        if: steps.mint-cache-v2.outputs.cache-hit != 'true'
        run: mint bootstrap

      - name: Run Swiftformat linter
        run: mint run swiftformat . --lint

      - name: Run Swiftlint
        run: mint run swiftlint lint --reporter github-actions-logging

      - name: Run iOS Tests
        run: |
          xcodebuild \
          -workspace Nest.xcworkspace \
          -scheme 'Log (iOS)' \
          -sdk iphonesimulator \
          -destination 'platform=iOS Simulator,name=iPhone 13,OS=15.5' \
          test \
          | mint run xcbeautify

      - name: Run macOS Tests
        run: |
          xcodebuild \
          -workspace Nest.xcworkspace \
          -scheme 'Log (macOS)' \
          test \
          | mint run xcbeautify
